#!/bin/bash
if [ ! -f $HOME/.axel-clui.conf ];
then
	echo "MAX_CONNECTIONS_PER_SERVER=16" > $HOME/.axel-clui.conf
fi

case $1 in
-c)
	while true
	do
		echo "Configuration:"
		echo "1. Max connections per server"
		echo "2. Exit"
		read c
		case $c in
		1)
			echo "Enter your desired max connections per server"
			read n
			sed -i "/MAX_CONNECTIONS_PER_SERVER/s/[0-9]\+/$n/g" $HOME/.axel-clui.conf
		;;
		2)
			break
		;;
		*)
		;;
		esac	
	done
;;
--help|-h|'')
	
	echo -e "\nUsage:"
	echo -e "\t$(basename $0) -c \t\tfor config menu"
	echo -e "\t$(basename $0) --help|-h \tfor this menu"
	echo -e "\t$(basename $0) URL \t\tto start downloading\n"
;;
*)
	DOWNLOAD_DIR=$HOME/Downloads
	SUBDIR=""
	echo $1 | grep -i -E '\.(BIN|ZIP|GZ|7Z|XZ|Z|TAR|TGZ|BZ2|LZH|A[0-9]?|RAR|R[0-9][0-9])[^a-zA-Z0-9\s\:]?' &> /dev/null
	if [ $? == 0 ];
	then
		SUBDIR=Compressed
	fi

	echo $1 | grep -i -E '\.(doc|pdf|ppt|pps|docx|pptx)[^a-zA-Z0-9\s\:]?' &> /dev/null
	if [ $? == 0 ];
	then
		SUBDIR=Documents
	fi

	echo $1 | grep -i -E '\.(mp3|wav|wma|mpa|ram|ra|aac|aif|m4a|ogg)[^a-zA-Z0-9\s\:]?' &> /dev/null
	if [ $? == 0 ];
	then
		SUBDIR=Music
	fi

	echo $1 | grep -i -E '\.(ISO|RPM|DEB|EXE|MSI|APK)[^a-zA-Z0-9\s\:]?' &> /dev/null
	if [ $? == 0 ];
	then
		SUBDIR=Programs
	fi

	echo $1 | grep -i -E '\.(avi|mpg|mpe|mpeg|asf|wmv|mov|qt|rm|mp4|flv|m4v|webm|ogv|mkv)[^a-zA-Z0-9\s\:]?' &> /dev/null
	if [ $? == 0 ];
	then
		SUBDIR=Video
	fi
	
	pidof_axel=0
	pidof_axel=$(pgrep -f "^axel -a -n [0-9]+ $1" || echo 0)
	if [ $pidof_axel -gt 0 ];
	then
		kill -SIGINT $pidof_axel
	fi
	
	cps=$(awk -F= '/MAX_CONNECTIONS_PER_SERVER/{print $2}' $HOME/.axel-clui.conf)
	gnome-terminal -x bash -c "mkdir -p $DOWNLOAD_DIR/$SUBDIR 2> /dev/null; cd $DOWNLOAD_DIR/$SUBDIR; axel -a -c -n $cps \"$1\"" 2> /dev/null
esac
